name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'speedrun'
      - 'react'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'wooferzfg/tww-rando-tracker' && github.ref == 'refs/heads/react'

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm packages
        run: |
          set -e
          npm install

      - name: Build UI
        run: |
          set -e
          npm run build:production

      - name: Run tests
        run: |
          set -e
          npm test

      - name: Run eslint
        run: |
          set -e
          npm run lint

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages-react
          publish_dir: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy branches
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone -b master -q "https://github.com/wooferzfg/tww-rando-tracker" ./repo
          git clone -b speedrun -q "https://github.com/wooferzfg/tww-rando-tracker" ./repo/speedrun
          git clone -b gh-pages-react -q "https://github.com/wooferzfg/tww-rando-tracker" ./repo/react
          cd repo
          git checkout --orphan gh-pages-test
          git add speedrun/
          git add react/
          git add .
          git commit -m "Deploy site"
  #       git push --force https://action:${{ secrets.GH_PAGES_DEPLOY }}@github.com/wooferzfg/tww-rando-tracker.git
